server:
  port: ${PORT:${SERVER_PORT:0}}
spring:


  application:
    name: api-catalog
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/baseback
    username: root
    password: Wire2681
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

info:
  application:
    name: api-catalog

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


resilience4j:
  retry:
    config:
      default:
        max-retry-attempts: 3
        wait-duration: 10s
        retry-exception:
          - java.net.SocketTimeoutException
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
      instances:
        retryInscription:
          base-config: default
          max-retry-attempts: 5
          wait-duration: 2s
          retry-exception:
            -java.net.ConnectException

  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        automatic-transition-from-open-half-open-enabled: true
        failure-rate-threshold: 50
    instances:
      clientInscription:
        base-config: default
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        wait-duration-in-open-state: 1m
        failure-rate-threshold: 50
