server:
  port: ${PORT:0}
spring:
  application:
    name: aprendices
  datasource:
    driverClassName: com.mysql.jc.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/edubit
    username: root
    password: Wire2681
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

info:
  application:
    name: aprendices



info:
  application:
    name: api-serie
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/